# Generated by Django 5.1.6 on 2025-05-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_motionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionevent',
            name='motion',
            field=models.BooleanField(default=False),
        ),
    ]
